name: chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8

  rsa_encrypt: ^2.0.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  marquee: ^2.1.0
  pointycastle: ^3.0.1

  firebase_core: 1.6.0
  firebase_auth: 3.1.0
  firebase_storage: 9.0.0
  cloud_firestore: 2.5.1


  google_sign_in: 5.1.0
  lottie: 1.1.0
  introduction_screen: 2.1.0
  avatar_glow: 2.0.1
  emoji_picker_flutter: 1.0.7
  get_storage: 2.0.3
  intl: 0.17.0
  image_picker: 0.8.3+2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

